version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: lumen_app
    working_dir: /var/www
    volumes:
      - ./lumen-app:/var/www
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=social
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: lumen_postgres
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:stable-alpine
    container_name: lumen_nginx
    ports:
      - "8080:80"
    volumes:
      - ./lumen-app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  pgdata: