version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: lumen_app
    working_dir: /var/www
    volumes:
      - ./lumen-app:/var/www
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=social
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: lumen_postgres
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/pgmaster:/var/lib/postgresql/data
      - ./docker/import:/import

  pgslave:
    image: postgres:16
    container_name: pgslave
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - "15432:5432"
    volumes:
      - ./volumes/pgslave:/var/lib/postgresql/data
    depends_on:
      - db

  pgasyncslave:
    image: postgres:16
    container_name: pgasyncslave
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - "25432:5432"
    volumes:
      - ./volumes/pgasyncslave:/var/lib/postgresql/data
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: lumen_nginx
    ports:
      - "8080:80"
    volumes:
      - ./lumen-app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - db

volumes:
  pgdata: